services:
  - type: web
    name: twitter-clone
    env: node
    region: ohio # or your preferred region
    plan: free # or starter/standard
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You'll add this in Render dashboard
      - key: JWT_SECRET
        sync: false # You'll add this in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
